### ISSUE TITLE
Feature Request - Add support for rewatching

### ISSUE THREAD

**Issue by Amateur-God** [Beannsss/PlexAniSync#18]
the script currently checks ani list for watched episode number and if watched episode on anilist is higher than the episode youve just watched it doesnt mark it as watched again, so when you are rewatching a show it doesnt get marked as such in AniList, the way i rewatch is a mark it as not watched in emby so i can start from the beginning again.

would it be possible to add support for rewatching shows

**Comment by bpwhelan** [comment]
Yeah this should be possible. Should be able to check for "rewatching" status on the anilist series and if rewatching then update and keep the "rewatching status". I'm not sure how anilist handles this so I'd have to mess around a bit. All my rewatches i've just marked rewatched after finished so i havent had the need for this yet.

This will likely come before the two way sync since that is a quite a bit more involved, and this is definitely useful.

I know Emby keeps track of rewatches somewhere so maybe there could be something cool with that.

**Comment by bpwhelan** [comment]
@Amateur-God this is actually somewhat already supported, if you mark a show as "rewatching" in anilist, it will maintain that status as you watch in emby, and still update the episode watch status in emby. I assume once you finish rewatching the show anilist will increment the "Total Rewatches" number but im not sure on that.

This is how I planned on implementing it anyway, so I don't really see me doing any more work around this subject for right now. Try that out and see how it works and let me know if you have any questions. Will likely close without any dev work.
